# ⛔️ DEPRECATED
# yaml-language-server: $schema=https://raw.githubusercontent.com/googleapis/repo-automation-bots/main/packages/auto-label/src/config-schema.json
# ref: <https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-label>

language:
  pullrequest: true
  labelprefix: "lang: "

path:
  pullrequest: true
  paths:
    docs: "type: docs"

staleness:
  pullrequest: true

requestsize:
  enabled: true
