# ref: <https://github.com/crazy-max/ghaction-github-labeler/blob/master/samples/original.yml>
# ref: <https://github.com/Financial-Times/github-label-sync>
# ref: <https://github.com/googleapis/repo-automation-bots/blob/main/packages/label-sync/src/labels.json>
# ref: <https://github.com/seantrane/github-label-presets/blob/main/labels.yml>
# ref: <https://github.com/yoshuawuyts/github-standard-labels/blob/master/README.md>
# ref: <https://seantrane.com/posts/logical-colorful-github-labels-18230/>

# --------------------------------- Standard --------------------------------- #
- name: "bug"
  color: "#d73a4a"
  description: Something isn't working
  aliases:
    - "type: bug"
    - "type: fix"
- name: "documentation"
  color: "#0075ca"
  description: Improvements or additions to documentation
  aliases:
    - "type: docs"
- name: "duplicate"
  color: "#cfd3d7"
  description: This issue or pull request already exists
  types:
    - "state: duplicate"
    - "status: duplicate"
- name: "enhancement"
  color: "#a2eeef"
  description: New feature or request
  aliases:
    - "type: feature"
    - "type: feature request"
- name: "good first issue"
  color: "#7057ff"
  description: Good for newcomers
- name: "help wanted"
  color: "#008672"
  description: Extra attention is needed
  aliases:
    - "help"
- name: "invalid"
  color: "#e4e669"
  description: This doesn't seem right
  aliases:
    - "state: invalid"
    - "status: invalid"
- name: "question"
  color: "#d876e3"
  description: Further information is requested
  aliases:
    - "type: discussion"
    - "type: question"
- name: "wontfix"
  color: "#ffffff"
  description: This will not be worked on
  aliases:
    - "state: will not fix"
    - "state: wontfix"
    - "status: will not fix"
    - "status: wontfix"

# --------------------------------- Priority --------------------------------- #
- name: "priority: critical"
  color: "#b60205"
  description: Highest priority. Critical issue.
  aliases:
    - "priority: now"
    - "priority: p0"
- name: "priority: high"
  color: "#ffa03e"
  description: Important issue which blocks shipping the next release. Will be fixed prior to next release.
  aliases:
    - "priority: 2day"
    - "priority: p1"
- name: "priority: medium"
  color: "#fef2c0"
  description: Moderately-important priority. Fix may not be included in next release.
  aliases:
    - "priority: p2"
    - "priority: soon"
- name: "priority: low"
  color: "#ffffc7"
  description: Desirable enhancement or fix. May not be included in next release.
  aliases:
    - "priority: p3"

# ----------------------------------- Work ----------------------------------- #
- name: "work: chaotic"
  description: The situation is chaotic, novel practices used.
  color: "#fbca04"
  aliases:
    - "chaotic"
- name: "work: complex"
  description: The situation is complex, emergent practices used.
  color: "#d4c5f9"
  aliases:
    - "complex"
- name: "work: complicated"
  description: The situation is complicated, good practices used.
  color: "#ffb8c6"
  aliases:
    - "complicated"
- name: "work: obvious"
  description: The situation is obvious, best practices used.
  color: "#91ca55"
  aliases:
    - "obvious"

# --------------------------------- Generated -------------------------------- #
- name: "bot"
  color: "#ffcc00"

# ------------------------------ Release Please ------------------------------ #
# ref: <https://github.com/googleapis/release-please>
- name: "autorelease: pending"
  color: "#ededed"
  description: is the initial state of the Release PR before it is merged
- name: "autorelease: tagged"
  color: "#ededed"
  description: means that the Release PR has been merged and the release has been tagged in GitHub
- name: "autorelease: snapshot"
  color: "#ededed"
  description: is a special state for snapshot version bumps
- name: "autorelease: published"
  color: "#ededed"
  description: means that a GitHub release has been published based on the Release PR
