# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# https://megalinter.io/latest/config-file/

# ----------------------------- Common Variables ----------------------------- #
APPLY_FIXES: all
DISABLE_ERRORS: true
DISABLE_LINTERS:
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
  - TYPESCRIPT_STANDARD
IGNORE_GENERATED_FILES: true
PLUGINS:
  - https://raw.githubusercontent.com/liblaf/megalinter-plugins/refs/heads/main/mega-linter-plugin-markdown-prettier/markdown.megalinter-descriptor.yml
SHOW_ELAPSED_TIME: true

# ---------------------------------- Linters --------------------------------- #
BASH_SHFMT_ARGUMENTS: --simplify --indent 2 --case-indent --space-redirects
COPYPASTE_JSCPD_DISABLE_ERRORS: true
JSON_FILTER_REGEX_EXCLUDE: '\.github/release\-please/\.manifest\.json'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
PYTHON_PYRIGHT_DISABLE_ERRORS: true
REPOSITORY_TRIVY_DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true
SPELL_LYCHEE_DISABLE_ERRORS: true
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '.*\-lock\..*|.*\.lock'
