# ref: <https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template>

name: 🐛 Bug Report

description: Create a report to help us improve

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  # ref: <https://github.com/lobehub/lobe-chat/blob/e653418c67f3e6111cbc5e2a54d7abd0a5ce82f0/.github/ISSUE_TEMPLATE/1_bug_report.yml>
  - type: textarea
    attributes:
      label: "📦 Environment"
      description: |
        examples:
          - **OS**: Arch Linux
          - **Python**: 3.12.6
      value: |
        - **OS**:
        - **Python**:
      render: markdown
  - type: textarea
    attributes:
      label: "🐛 Bug Description"
      description: A clear and concise description of the bug, if the above option is `Other`, please also explain in detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "📷 Recurrence Steps"
      description: A clear and concise description of how to recurrence.
  - type: textarea
    attributes:
      label: "🚦 Expected Behavior"
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: "📝 Additional Information"
      description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here.

assignees:
  - liblaf

labels:
  - "type: bug"
  - "priority: p2"

title: "[BUG] <title>"
