# ref: <https://github.com/lobehub/lobe-chat/blob/e653418c67f3e6111cbc5e2a54d7abd0a5ce82f0/.github/ISSUE_TEMPLATE/2_feature_request.yml>

name: 🌠 Feature Request

description: Suggest an idea for this project

body:
  - type: textarea
    attributes:
      label: "🥰 Feature Description"
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "🧐 Proposed Solution"
      description: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "📝 Additional Information"
      description: Add any other context about the problem here.
    validations:
      required: false

assignees:
  - liblaf

labels:
  - "type: feature"
  - "priority: p3"

title: "[Feature] "
